#!/usr/bin/env php
<?php

require dirname(__FILE__) . '/packager.php';

$executable = array_shift($argv);
$command = array_shift($argv);
$a0 = !empty($argv[0]) ? $argv[0] : null;

if ($a0 == '-h' || $a0 == '--help'){
	usage($command);
	exit;
}

try
{
$home = exec('echo '.(strstr(PHP_OS, 'WIN') ? '%UserProfile%': '$HOME'));
if ($home == '$HOME') $home = array_get($_SERVER, 'USERPROFILE');

$packages = YAML::decode_file("$home/.packages.yml");
if (empty($packages)) $packages = array();

switch ($command){
	
	case 'register':

		$folder = array_shift($argv);
		$realpath = realpath($folder);
		
		if (!$realpath){
			throw new Exception("file or directory $folder not found\n");
		}
		
		$pkg = new Packager($realpath);
		$name = $pkg->get_package_name();
		$path = $pkg->get_package_manifest();
		
		$packages[$name] = $path;
		
		file_put_contents("$home/.packages.yml", YAML::encode($packages));

		echo "the package $name has been registered as $path\n";

	break;
	
	case 'unregister':
	
		$name = array_shift($argv);
		
		if (empty($packages[$name])){
			throw new Exception("there is no package called $name\n");
		}

		unset($packages[$name]);
	
		file_put_contents("$home/.packages.yml", YAML::encode($packages));
	
		echo "the package $name has been unregistered\n";
	
	break;
	
	case 'list':
	
		$package_name = array_shift($argv);
	
		if (empty($package_name)){
			foreach ($packages as $name => $path) {
				echo "$name: $path\n";
			}
		} else {
			if (!empty($packages[$package_name])){
				$package_path = $packages[$package_name];
				$pkg = new Packager($package_path);
				$files = $pkg->get_all_files();
				foreach ($files as $file){
					$file_name = $pkg->get_file_name($file);
					echo "- $file_name: [" . implode(", ", $pkg->get_file_provides($file)) . "]\n";
				}
			} else {
				throw new Exception("The package $package_name has not been found.\n");
			}
		}
		
	break;
	
	case 'build':

		$selected = array(
			'components' => array(),
			'files' => array(),
			'add-packages' => array(),
			'remove-packages' => array(),
			'remove-components' => array(),
			'remove-files' => array(),
			'remove-files-and-deps' => array(),
			'blocks' => array(),
			'use-only' => null
		);
		
		$build = 'components';
		
		foreach ($argv as $arg){

			if ($arg == '+packages'){
				$build = 'add-packages';
				continue;
			}
			
			if ($arg == '-blocks'){
				$build = 'blocks';
				continue;
			}
			
			if ($arg == '+use-only'){
				$build = 'use-only';
				if ($selected['use-only'] == null) $selected['use-only'] = array();
				continue;
			}
			
			if ($arg == '-packages'){
				$build = 'remove-packages';
				continue;
			}
			
			if ($arg == '+components'){
				$build = 'components';
				continue;
			}
			if ($arg == '-components'){
				$build = 'remove-components';
				continue;
			}

			if ($arg == '-files'){
				$build = 'remove-files';
				continue;
			}
			
			if ($arg == '-files+deps'){
				$build = 'remove-files-and-deps';
				continue;
			}
			
			if ($arg == '+files'){
				$build = 'files';
				continue;
			}

			$selected[$build][] = $arg;
		}
		
		$paths = array();
					
		foreach ($packages as $name => $path){
			if (!$selected['use-only'] || array_contains($selected['use-only'], $name)) $paths[] = $path;
		}
		
		$pkg = new Packager($paths);
		
		foreach ($selected['remove-packages'] as $package_name) $pkg->remove_package($package_name);
		foreach ($selected['add-packages'] as $package_path) $pkg->add_package($package_path);
		
		$re = "/^([^\/]+)\/\*$/";
		$wildcards = array();
		
		$files = $selected['files'];
		$components = $selected['components'];
		$remove_components = $selected['remove-components'];
		$remove_files = $selected['remove-files'];
		$remove_files_and_deps = $selected['remove-files-and-deps'];
		$blocks = $selected['blocks'];
		
		foreach ($components as $component){
			preg_match($re, $component, $matches);
			if (!empty($matches)){
				array_erase($components, $component);
				array_include($wildcards, $matches[1]);
			}
		}
		
		foreach ($files as $file){
			preg_match($re, $file, $matches);
			if (!empty($matches)){
				array_erase($files, $file);
				array_include($wildcards, $matches[1]);
			}
		}
		
		$vf = $pkg->validate($files, $components, $wildcards);
		if (is_array($vf)) {
			throw new Exception(implode("\n", $vf) . "\n");
		}
		
		$files = $pkg->resolve_files($files, $components, $wildcards, array(), array(
			'components' => $remove_components,
			'files' => $remove_files,
			'files_and_deps' => $remove_files_and_deps
		));

		write2stderr("Build using: " . implode(', ', $pkg->get_packages()) . "\n");
		write2stderr("Included Files/Components:\n");
		
		foreach ($files as $file){
			$file_name = $pkg->get_file_name($file);
			$file_package = $pkg->get_file_package($file);
			write2stderr("- $file_package/$file_name: [" . implode(", ", $pkg->get_file_provides($file)) . "]\n");
		}
		
		echo $pkg->build($files, array(), array(), $blocks);
	
	break;
	
	case 'help':
	case '-h':
	case '--help':
		usage(array_shift($argv));
	break;
	
	default:
		usage();
	break;
}
}
catch (Exception $e)
{
	write2stderr($e->message);
	exit(1);
}

function usage($command = ''){
	$dir = dirname(__FILE__);
	if (empty($command) || !file_exists("$dir/help/$command.txt")) $command = 'default';
	echo file_get_contents("$dir/help/$command.txt");
}

function write2stderr($message)
{
	if (PHP_SAPI === 'cli') {
		$std_err = fopen('php://stderr', 'w');
		fwrite($std_err, $message);
		fclose($std_err);
	} else {
		trigger_error($message, E_USER_WARNING);
	}
}

?>
